package com.giovyenet.utils.jdbc;

import java.util.List;

public class CreatePS {	
	
	public static void main(String[] args) {
		String sentence = "" + 
				"	id                   bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL ,\r\n" + 
				"	concepto_analisis    varchar(45) DEFAULT NULL  ,\r\n" + 
				"	fecha_concepto       timestamp   ,\r\n" + 
				"	fecha_solicitud_consulta timestamp   ,\r\n" + 
				"	estado               varchar(45)  NOT NULL ,\r\n" + 
				"	monto                integer  NOT NULL ,\r\n" + 
				"	plazo                integer  NOT NULL ,\r\n" + 
				"	tasa                 numeric(20_6)  NOT NULL ,\r\n" + 
				"	id_tipo_contrato     integer   ,\r\n" + 
				"	tipo_credito         varchar(45) DEFAULT NULL  ,\r\n" + 
				"	fecha_ingreso        timestamp   ,\r\n" + 
				"	fecha_terminacion    timestamp   ,\r\n" + 
				"	actividad            varchar(45) DEFAULT NULL  ,\r\n" + 
				"	cargo                varchar(45) DEFAULT NULL  ,\r\n" + 
				"	fecha_aprobacion     date   ,\r\n" + 
				"	fecha_estimada_radicacion timestamp   ,\r\n" + 
				"	fecha_estimada_desembolso timestamp   ,\r\n" + 
				"	destino_credito      text   ,\r\n" + 
				"	numero_radicacion    integer   ,\r\n" + 
				"	asegurabilidad       varchar(45) DEFAULT NULL  ,\r\n" + 
				"	observaciones        text   ,\r\n" + 
				"	id_pagaduria         integer  NOT NULL ,\r\n" + 
				"	id_cliente           integer  NOT NULL ,\r\n" + 
				"	id_asesor_principal  integer  NOT NULL ,\r\n" + 
					"	id_cobrador          integer   ,\r\n" + 
					"	tiene_cuenta_bancaria bool  NOT NULL ,\r\n" + 
				"	total_activos        integer   ,\r\n" + 
				"	total_pasivos        integer   ,\r\n" + 
				"	ingresos_mes         integer   ,\r\n" + 
				"	otros_ingresos       integer   ,\r\n" + 
				"	descripcion_otros_ingresos text   ,\r\n" + 
				"	numero_hijos         smallint   ,\r\n" + 
				"	personas_a_cargo     smallint   ,\r\n" + 
				"	profesion            varchar(100) DEFAULT NULL  ,\r\n" + 
				"	nivel_educativo      varchar(45) DEFAULT NULL  ,\r\n" + 
				"	estado_civil         varchar(20) DEFAULT NULL  ,\r\n" + 
				"	tipo_vivienda        varchar(20) DEFAULT NULL  ,\r\n" + 
				"	meses_residencia_actual smallint   ,\r\n" + 
				"	nombre_arrendador    varchar(150) DEFAULT NULL  ,\r\n" + 
				"	telefono_arrendador  varchar(50) DEFAULT NULL  ,\r\n" + 
				"	matricula_inmobiliaria varchar(45) DEFAULT NULL  ,\r\n" + 
				"	hipoteca_a_favor_de  varchar(100) DEFAULT NULL  ,\r\n" + 
				"	tiene_vehiculo       bool  NOT NULL ,\r\n" + 
				"	placa_vehiculo       varchar(10) DEFAULT NULL  ,\r\n" + 
				"	pignorado_a_favor_de varchar(100) DEFAULT NULL  ,\r\n" + 
				"	persona_expuesta     bool  NOT NULL ,\r\n" + 
				"	declara_renta        bool  NOT NULL ,\r\n" + 
				"	productos_moneda_extranjera bool  NOT NULL ,\r\n" + 
				"	banco_moneda_extranjera varchar(45) DEFAULT NULL  ,\r\n" + 
				"	pais_moneda_extranjera varchar(45) DEFAULT NULL  ,\r\n" + 
				"	ciudad_moneda_extranjera varchar(100) DEFAULT NULL  ,\r\n" + 
				"	tipo_producto_moneda_extranjera varchar(80) DEFAULT NULL  ,\r\n" + 
				"	numero_producto_moneda_extranjera varchar(45) DEFAULT NULL  ,\r\n" + 
				"	monto_operacion_moneda_extranjera integer   ,\r\n" + 
				"	moneda               varchar(3) DEFAULT NULL  ,\r\n" + 
				"	transacciones_moneda_extranjera bool  NOT NULL ,\r\n" + 
				"	transaccion_moneda_extranjera text   ,\r\n" + 
				"	descripcion_transaccion text   ,\r\n" + 
				"	telefono_fijo        varchar(30) DEFAULT NULL  ,\r\n" + 
				"	telefono_celular     varchar(30) DEFAULT NULL  ,\r\n" + 
				"	email                varchar(120) DEFAULT NULL  ,\r\n" + 
				"	direccion            varchar(120) DEFAULT NULL  ,\r\n" + 
				"	id_departamento      varchar(100)  NOT NULL ,\r\n" + 
				"	id_ciudad            varchar(100)  NOT NULL ,\r\n" + 
				"	id_pagaduria_sucursal integer   ,\r\n" + 
				"	monto_aprobado       integer   ,\r\n" + 
				"	fecha_entrevista     timestamp   ,\r\n" + 
				"	direccion_entrevista varchar(120) DEFAULT NULL  ,\r\n" + 
				"	numero_casa_apartamento varchar(20) DEFAULT NULL  ,\r\n" + 
				"	id_ciudad_entrevista varchar(120) DEFAULT NULL  ,\r\n" + 
				"	id_departamento_entrevista varchar(120) DEFAULT NULL  ,\r\n" + 
				"	comentarios_entrevista text   ,\r\n" + 
				"	id_afp               integer   ,\r\n" + 
				"	regimen_pension      varchar(20) DEFAULT NULL  ,\r\n" + 
				"	valor_extra_prima_asegurabilidad numeric(20_6) DEFAULT NULL  ,\r\n" + 
				"	comentario_asegurabilidad text   ,\r\n" + 
				"	requiere_revision_medica bool   ,\r\n" + 
				"	tiene_enfermedad     bool   ,\r\n" + 
				"	tiene_incapacidad_permanente bool   ,\r\n" + 
				"	comentario_enfermedad text   ,\r\n" + 
				"	comentario_incapacidad_permanente text   ,\r\n" + 
				"	id_causal_rechazo    integer   ,\r\n" + 
				"	salario_referenciacion bool   ,\r\n" + 
				"	tipo_contrato_referenciacion bool   ,\r\n" + 
				"	fecha_ingreso_referenciacion bool   ,\r\n" + 
				"	cargo_referenciacion bool   ,\r\n" + 
				"	descuento_proyectado_refereciacion numeric(20_4) DEFAULT NULL  ,\r\n" + 
				"	quien_confirma_referenciacion varchar(60) DEFAULT NULL  ,\r\n" + 
				"	cargo_quien_confirma_referenciacion varchar(120) DEFAULT NULL  ,\r\n" + 
				"	fecha_hora_referenciacion timestamp   ,\r\n" + 
				"	tiene_seguro_voluntario bool   ,\r\n" + 
				"	esta_asegurada_itp   bool   ,\r\n" + 
				"	monto_asegurabilidad integer   ,\r\n" + 
				"	plazo_asegurabilidad integer   ,\r\n" + 
				"	id_causal_rechazo_asegurabilidad integer   ,\r\n" + 
				"	canal                varchar(20) DEFAULT NULL  ,\r\n" + 
				"	reprocesado          bool   ,\r\n" + 
				"	estado_liquidacion   varchar(45) DEFAULT NULL  ,\r\n" + 
				"	prima                integer   ,\r\n" + 
				"	otros_descuentos     integer   ,\r\n" + 
				"	id_cuenta            integer   ,\r\n" + 
				"	codigo_empleado      varchar(20) DEFAULT NULL  ,\r\n" + 
				"	grado                varchar(20) DEFAULT NULL  ,\r\n" + 
				"	saldo_favor_mora     numeric(20_4) DEFAULTNOT NULL ,\r\n" + 
				"	centro_costos        varchar(20) DEFAULT NULL  ,\r\n" + 
				"	codigo_militar       varchar(20) DEFAULT NULL  ,\r\n" + 
				"	codigo_programa_nomina integer   ,\r\n" + 
				"	tipo_pension         varchar(50) DEFAULT NULL  ,\r\n" + 
				"	numero_afiliacion    varchar(15) DEFAULT NULL  ,\r\n" + 
				"	numero_resolucion    varchar(20) DEFAULT NULL  ,\r\n" + 
				"	proforenses          varchar(15) DEFAULT NULL  ,\r\n" + 
				"	resultado_proforenses bool   ,\r\n" + 
				"	usuario_asegurador   integer   ,\r\n" + 
				"	credito_activo       bool   ,\r\n" + 
				"	credito_importado    bool   ,\r\n" + 
				"	credito_desembolsado bool   ,\r\n" + 
				"	credito_riesgo       varchar(45) DEFAULT NULL  ,\r\n" + 
				"	id_consulta_data_credito integer   ,\r\n" + 
				"	id_credito_original  integer   ,\r\n" + 
				"	cuenta_contable_capital varchar(10) DEFAULT NULL ,\r\n" + 
				"	aprobacion_rechazo_titulo bool   ,\r\n" + 
				"	en_negociacion       bool   ,\r\n" + 
				"	fecha_recepcion      timestamp   ,\r\n" + 
				"	causal_recompra      varchar(50) DEFAULT NULL  ,\r\n" + 
				"	devuelto_fabrica     bool   ,\r\n" + 
				"	id_central_data      integer   ,\r\n" + 
				"	id_central_cifin     integer   ,\r\n" + 
				"	observacion_huella_centrales varchar(250) DEFAULT NULL  ,\r\n" + 
				"	condonado            bool  NOT NULL ,\r\n" + 
				"	id_linea_credito     integer   ,\r\n" + 
				"	id_tipo_visacion     integer   ,\r\n" + 
				"	id_oficina           integer DEFAULT 1 NOT NULL ,\r\n" + 
				"	clave_consulta_desprendible varchar(50) DEFAULT NULL  ,\r\n" + 
				"	nit_afiliacion       varchar(60) DEFAULT NULL  ,\r\n" + 
				"	periodo_comercial    date   ,\r\n" + 
				"	id_causal_mora       integer   ,\r\n" + 
				"	credito_condonado    bool DEFAULT false  ,\r\n" + 
				"	fecha_aprobacion_castigo timestamp   ,\r\n" + 
				"	id_castigador        integer   ,\r\n" + 
				"	fecha_viabilidad     timestamp   ,\r\n" + 
				"	cantidad_reestructuracion integer   ,\r\n" + 
				"	fecha_ultima_reestructuracion date "; 		
		System.out.println(sentence);
		
		CodeStatement codeStatement = new CodeStatement(sentence);
		
		List<Field> lstField = codeStatement.getLstField();
		
		for (Field f : lstField) {
			System.out.println("--");
			System.out.print(f.getJavaName() + ",");
			System.out.print(f.getSqlName() + ",");
			System.out.print(f.getJavaType() + ",");
			System.out.print(f.getSqlType() + ",");
			System.out.print(f.getNotNull() + ",");
		}
		
		List <String> lstDTOFields = codeStatement.getLstDTOFields();
		for (String element : lstDTOFields) {
			System.out.println(element);			
		}
		

		List <String> lstPSNoPrefix = codeStatement.getLstPS(null);
		for (String element : lstPSNoPrefix) {
			System.out.println(element);			
		}
		
		
		
		List <String> lstPS = codeStatement.getLstPS("dto");
		for (String element : lstPS) {
			System.out.println(element);			
		}

		List <String> lstRSNoPrefix = codeStatement.getLstRS("dto");
		for (String element : lstRSNoPrefix) {
			System.out.println(element);			
		}
		
		
	}
	
	
	
}
